/**
 * 生成 AutoWSGR GUI 运行契约的隔离行为探针。
 *
 * 探针只在短生命周期的 Python 检查进程中替换外部依赖，验证
 * Launcher 公共方法是否真正消费 GUI 环境变量，不修改实际后端进程。
 */
export function buildBackendRuntimeContractProbeLines(
  functionName = '_verify_gui_runtime_contract',
): string[] {
  return [
    `def ${functionName}():`,
    '    import os as _contract_os',
    '    from types import SimpleNamespace as _ContractNamespace',
    '    from unittest.mock import patch as _contract_patch',
    '    from autowsgr.scheduler.launcher import Launcher as _ContractLauncher',
    '    _log = _ContractNamespace(',
    "        dir='.',",
    "        level='INFO',",
    '        effective_channels=[],',
    '    )',
    '    _ocr = _ContractNamespace(',
    '        gpu=False,',
    "        mirror='modelscope',",
    '        ship_name_match_confidence=0.0,',
    '        ship_name_corrections={},',
    '        ship_name_aliases={},',
    '    )',
    '    _config = _ContractNamespace(log=_log, ocr=_ocr)',
    "    _save_key = 'AUTOWSGR_SAVE_IMAGES'",
    "    _ocr_key = 'AUTOWSGR_OCR_GPU_MODE'",
    '    _previous_save = _contract_os.environ.get(_save_key)',
    '    _previous_ocr = _contract_os.environ.get(_ocr_key)',
    '    try:',
    '        _save_values = []',
    '        def _capture_logger(*args, **kwargs):',
    "            _save_values.append(kwargs.get('save_images'))",
    '        with _contract_patch(',
    "            'autowsgr.scheduler.launcher.ConfigManager.load',",
    '            return_value=_config,',
    '        ), _contract_patch(',
    "            'autowsgr.scheduler.launcher.setup_logger',",
    '            side_effect=_capture_logger,',
    '        ):',
    "            _contract_os.environ[_save_key] = 'true'",
    '            _ContractLauncher().load_config()',
    "            _contract_os.environ[_save_key] = 'false'",
    '            _ContractLauncher().load_config()',
    '        if _save_values != [True, False]:',
    "            raise RuntimeError('AUTOWSGR_SAVE_IMAGES 行为不兼容')",
    '        _ocr_values = []',
    '        def _capture_ocr(*args, **kwargs):',
    "            _ocr_values.append(kwargs.get('gpu'))",
    '            return object()',
    '        _launcher = _ContractLauncher()',
    '        _launcher.set_config(_config)',
    '        with _contract_patch(',
    "            'autowsgr.scheduler.launcher.EasyOCREngine.create',",
    '            side_effect=_capture_ocr,',
    '        ):',
    "            _contract_os.environ[_ocr_key] = 'cuda'",
    '            _launcher.create_ocr()',
    "            _contract_os.environ[_ocr_key] = 'cpu'",
    '            _launcher.create_ocr()',
    '        if _ocr_values != [True, False]:',
    "            raise RuntimeError('AUTOWSGR_OCR_GPU_MODE 行为不兼容')",
    '    finally:',
    '        if _previous_save is None:',
    '            _contract_os.environ.pop(_save_key, None)',
    '        else:',
    '            _contract_os.environ[_save_key] = _previous_save',
    '        if _previous_ocr is None:',
    '            _contract_os.environ.pop(_ocr_key, None)',
    '        else:',
    '            _contract_os.environ[_ocr_key] = _previous_ocr',
  ];
}
